### ISSUE TITLE
ESPHome M5StickC

### ISSUE THREAD

**Issue by collinsjoshw** [apolselli/home-assistant-config#1]
I was unable to get the M5StickC to boot after flashing any ESPHome code.  Is there some kind of trick to getting it to turn on after or complete the flashing process?

Thanks!

**Comment by apolselli** [comment]
Hi, this is not a project. It is only my (not very updated) configuration store. You can take inspiration or copy from it, but please refer to the homeassistant and esphome projects for issues or support.
