### ISSUE TITLE
DHT12 and BMP280 Communication failed

### ISSUE THREAD

**Issue by mjendza** [apolselli/home-assistant-config#2]
Hi, 

I found the issue with connection to the devices:

ESPHome version is:  `ESPHome version 1.16.1`

![image](https://user-images.githubusercontent.com/366901/108623645-518f3200-7440-11eb-9c3b-85e409c47e81.png)

any idea how to fix it?

**Comment by apolselli** [comment]
Hi, this is not a project. It is only my (not very updated) configuration store. You can take inspiration or copy from it, but please refer to the homeassistant and esphome projects for issues or support.
